apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shift-festival-dev

resources:
  - ../../base
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shift-secrets
    envs:
      - .env

patchesStrategicMerge:
  - service-clusterip-patch.yaml

images:
  - name: ghcr.io/integrationproject-groep1/heartbeat
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/crm
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/identity-service
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/planning
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/facturatie
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/ip-groep1-frontend
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/kassa
    newTag: dev
  - name: ghcr.io/integrationproject-groep1/monitoring
    newTag: dev
