apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shift-festival-dev

resources:
  - ../../base
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: shift-secrets-dev
    envs:
      - .env

replacements:
- source:
    kind: Secret
    name: shift-secrets-dev
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.[].env.[].valueFrom.secretKeyRef.name
    - spec.template.spec.initContainers.[].env.[].valueFrom.secretKeyRef.name
  - select:
      kind: StatefulSet
    fieldPaths:
    - spec.template.spec.containers.[].env.[].valueFrom.secretKeyRef.name
    - spec.template.spec.initContainers.[].env.[].valueFrom.secretKeyRef.name
