server {
    listen 443 ssl;
    server_name _;

    # Hier bewijst Nginx wie hij is met jullie certificaten
    ssl_certificate /certs/cert.pem;
    ssl_certificate_key /certs/key.pem;

    location / {
        # Hier stuurt Nginx het verkeer intern door naar Dozzle op poort 8080
        proxy_pass http://dozzle:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}