server {
    listen 443 ssl;
    listen [::]:443 ssl;

    # Using the shared project certificates managed by Infra
    ssl_certificate /certs/cert.pem;
    ssl_certificate_key /certs/key.pem;

    location / {
        # Internal routing to the Odoo container
        proxy_pass http://kassa-web:8069;

        # Standard headers to ensure Odoo knows its public URL and port
        proxy_set_header Host $host:30030;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 30030;
        proxy_set_header X-Forwarded-Host $host;
        # Ensures Odoo doesn't redirect the user back to insecure HTTP
        proxy_redirect http:// $scheme://;
    }
}
