server {
    listen 80;
    listen [::]:80;

    location / {
        # Internal routing to the Odoo container
        proxy_pass http://kassa-web:8069;

        # Standard headers to ensure Odoo knows its public URL and port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Host $host;
        # Rewrite any HTTP redirects from Odoo to HTTPS
        proxy_redirect http:// https://;
    }
}
