apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- argocd/rollouts
- base/metrics-server
images:
- name: ghcr.io/integrationproject-groep1/ip-groep1-frontend
  newName: ghcr.io/integrationproject-groep1/ip-groep1-frontend
  digest: sha256:289fa225955572730b3240ce1793242c8511a0c6e2480819f77f8b6bbf376cf1
- name: ghcr.io/integrationproject-groep1/kassa
  newName: ghcr.io/integrationproject-groep1/kassa
  digest: sha256:5bacfbd5cba5d3e0180d44d4ccfc83f72be4a9f8850da984394abacdf5a9dac1
- name: ghcr.io/integrationproject-groep1/kassa-odoo
  newName: ghcr.io/integrationproject-groep1/kassa
  digest: sha256:fc9ec0756d69bf680e1887d04ee0b70143c6a5e14172eabcb112c7d2c8983ed4
- name: ghcr.io/integrationproject-groep1/facturatie
  newName: ghcr.io/integrationproject-groep1/facturatie
  digest: sha256:d6f681cd699ce87e24a1e0143ae0484905b819b75f74e33d4df8929ea8ff8fb4
- name: ghcr.io/integrationproject-groep1/crm
  newName: ghcr.io/integrationproject-groep1/crm
  digest: sha256:705fa1f2a4b2c55ab4313ac30df9dc04280aad8c4f27e66b85f0675e529bf340
- name: ghcr.io/integrationproject-groep1/planning
  newName: ghcr.io/integrationproject-groep1/planning
  digest: sha256:8cae0264907a5558c885f94102d74ba6580c4ed2c282741d0872b5f6296b87cf
- name: ghcr.io/integrationproject-groep1/identity-service
  newName: ghcr.io/integrationproject-groep1/identity-service
  digest: sha256:698bfe4bd48b7332dc8fb64f218a3a361c7304dac53de28e8acd224d412e926e
- name: ghcr.io/integrationproject-groep1/heartbeat
  newName: ghcr.io/integrationproject-groep1/heartbeat
  digest: sha256:db7c5ebb58708e031c404ac225bcdb04fac0f0d0c420b45c981fd409ab8799e6
- name: ghcr.io/integrationproject-groep1/mailing
  newName: ghcr.io/integrationproject-groep1/mailing
  digest: sha256:433e792a3a72cbc852bc5cd9a1cb69666e74393943b7962b676f46e7c4a32a3d
- name: ghcr.io/integrationproject-groep1/monitoring
  newName: ghcr.io/integrationproject-groep1/monitoring
  digest: sha256:73c2de935ee6bbb16ed2723c80ab6578d08b012be5576cacc14fdedc3987387e
- name: ghcr.io/integrationproject-groep1/chatbot
  newName: ghcr.io/integrationproject-groep1/chatbot
  digest: sha256:115553cb609cd763f064742cc3a8df90fc00da1dfb0ccd947bb7d4c68ddec776
- name: ghcr.io/integrationproject-groep1/ip-groep1-frontend-mcp
  newName: ghcr.io/integrationproject-groep1/ip-groep1-frontend-mcp
  digest: sha256:73d0b85af6454dcfc8d6ec14758f85e9ed272cc9059e7997342acba40f8d89fa
- name: ghcr.io/integrationproject-groep1/monitoring-mcp
  newName: ghcr.io/integrationproject-groep1/monitoring-mcp
  digest: sha256:b296d845828ad2b51d620c729d6048d0389cabe45cf0e4e8b3c35cb831504d30
- name: ghcr.io/integrationproject-groep1/facturatie-mcp
  newName: ghcr.io/integrationproject-groep1/facturatie-mcp
  digest: sha256:1e16b33e5c74d55ce3f4f386959f8a08fc252ba4ba808e98313865fa189a0f18
- name: ghcr.io/integrationproject-groep1/crm-mcp
  newName: ghcr.io/integrationproject-groep1/crm-mcp
  digest: sha256:5c313c8c20c4e19d60e7d48064ab4a04a6d437bcd66eff9cc27a04f28bede3ea
- name: ghcr.io/integrationproject-groep1/kassa-mcp
  newName: ghcr.io/integrationproject-groep1/kassa-mcp
  digest: sha256:cbf19fb08f8e23b88d977c160f3c2b1d3ded36fc921e384321fef313680b8b9b
patches:
- target:
    kind: Rollout
    name: frontend-drupal
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "750m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
