apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- argocd/rollouts
- base/metrics-server
images:
- name: ghcr.io/integrationproject-groep1/ip-groep1-frontend
  newName: ghcr.io/integrationproject-groep1/ip-groep1-frontend
  digest: sha256:2769995985d0e7adfdd3ee36e23a15878561137f38cbae525969d623d1edc4d1
- name: ghcr.io/integrationproject-groep1/kassa
  newName: ghcr.io/integrationproject-groep1/kassa
  digest: sha256:7ba76bac9822ed7fc847a2c2db52a3354bd27611d644aa2821e924682d442258
- name: ghcr.io/integrationproject-groep1/kassa-odoo
  newName: ghcr.io/integrationproject-groep1/kassa
  digest: sha256:e1831ddf9664ce9d8767d0d8ce663b120aec4c64f22972a39482565e54b03d84
- name: ghcr.io/integrationproject-groep1/facturatie
  newName: ghcr.io/integrationproject-groep1/facturatie
  digest: sha256:6cacbc16625fd589db2cfe041aec6d20c2b6be6610124b1526903addcf46393f
- name: ghcr.io/integrationproject-groep1/crm
  newName: ghcr.io/integrationproject-groep1/crm
  digest: sha256:97cc29d2b0be5423218a04dc48853b6aa9d056f41eef43baa453f40b9b65eb68
- name: ghcr.io/integrationproject-groep1/planning
  newName: ghcr.io/integrationproject-groep1/planning
  digest: sha256:f82971f89205c536c879b47884997548acae653011b6fa9b8e373025f752f77b
- name: ghcr.io/integrationproject-groep1/identity-service
  newName: ghcr.io/integrationproject-groep1/identity-service
  digest: sha256:902c3dd31ac98ece086260e42ee07f765e3d40db45d3f1e5dfebed0c0d57a9fa
- name: ghcr.io/integrationproject-groep1/heartbeat
  newName: ghcr.io/integrationproject-groep1/heartbeat
  digest: sha256:db7c5ebb58708e031c404ac225bcdb04fac0f0d0c420b45c981fd409ab8799e6
- name: ghcr.io/integrationproject-groep1/mailing
  newName: ghcr.io/integrationproject-groep1/mailing
  digest: sha256:3d45cfb1f1cfd5607226568878bad5a19ad0b352d03a7070af5cf00662fa78d3
- name: ghcr.io/integrationproject-groep1/monitoring
  newName: ghcr.io/integrationproject-groep1/monitoring
  digest: sha256:710aaa7e092dbfe6e485e41968bac559961105e123278512d2b7153dd837fcfe
- name: ghcr.io/integrationproject-groep1/chatbot
  newName: ghcr.io/integrationproject-groep1/chatbot
  digest: sha256:e8787f479fac0f0aa5d5f7020f1ece244a3901d52013fbc405ece5bc3f5ad257
patches:
- target:
    kind: Rollout
    name: frontend-drupal
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "750m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
