apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - rabbitmq.yaml
  - rabbitmq-ingress.yaml
  - cloudflared.yaml
  - ingress/ingress-nginx.yaml
  - external-ingress.yaml
