apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  labels:
    app: elastic-agent
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      serviceAccountName: elastic-agent
      terminationGracePeriodSeconds: 30
      # trivy:ignore:KSV-0009
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: elastic-agent
        image: docker.elastic.co/beats/elastic-agent:8.17.0
        args: ["-e", "-c", "/etc/elastic-agent/elastic-agent.yml"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOSTFS
          value: /hostfs
        - name: STATE_PATH
          value: /usr/share/elastic-agent/state
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shift-secrets
              key: ELASTIC_PASSWORD
        securityContext:
          runAsUser: 0
          # trivy:ignore:KSV-0014
          privileged: True
          readOnlyRootFilesystem: false
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1.5Gi
        livenessProbe:
          httpGet:
            host: 127.0.0.1
            path: /stats
            port: 6791
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 8
        readinessProbe:
          httpGet:
            host: 127.0.0.1
            path: /stats
            port: 6791
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
        volumeMounts:
        - name: config
          mountPath: /etc/elastic-agent/elastic-agent.yml
          subPath: elastic-agent.yml
          readOnly: true
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: state
          mountPath: /usr/share/elastic-agent/state
      volumes:
      - name: config
        secret:
          secretName: elastic-agent-config
      - name: hostfs
        # trivy:ignore:KSV-0121
        hostPath:
          path: /
      - name: state
        hostPath:
          path: /var/lib/elastic-agent/state
          type: DirectoryOrCreate
