apiVersion: v1
kind: Secret
metadata:
  name: elastic-agent-config
stringData:
  elastic-agent.yml: |
    outputs:
      default:
        type: elasticsearch
        hosts:
          - "http://elasticsearch-service:9200"
        username: "elastic"
        password: "${ELASTICSEARCH_PASSWORD}"

    inputs:
      - type: system/metrics
        streams:
          - metricsets:
              - cpu
              - memory
              - filesystem
              - diskio
              - load
            period: 30s
            hostfs: /hostfs

      - id: kubernetes-metrics
        type: kubernetes/metrics
        data_stream:
          namespace: default
        use_output: default
        streams:
          - id: kubernetes-node-metrics
            data_stream:
              type: metrics
              dataset: kubernetes.node
            metricsets:
              - node
            period: 30s
            hosts:
              - "https://${NODE_NAME}:10250"
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
            add_metadata: true
          - id: kubernetes-pod-metrics
            data_stream:
              type: metrics
              dataset: kubernetes.pod
            metricsets:
              - pod
            period: 30s
            hosts:
              - "https://${NODE_NAME}:10250"
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
            add_metadata: true
          - id: kubernetes-container-metrics
            data_stream:
              type: metrics
              dataset: kubernetes.container
            metricsets:
              - container
            period: 30s
            hosts:
              - "https://${NODE_NAME}:10250"
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            ssl.verification_mode: none
            add_metadata: true
