apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-heartbeat
  template:
    metadata:
      labels:
        app: monitoring-heartbeat
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: heartbeat
        image: ghcr.io/integrationproject-groep1/heartbeat:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        env:
        - name: SYSTEM_NAME
          value: "monitoring"
        - name: TARGETS
          value: "monitoring-agent:3000" # Assuming monitoring agent has a port? Wait, let's check.
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: shift-secrets
              key: RABBITMQMONITORING_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: shift-secrets
              key: RABBITMQMONITORING_PASS
