apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch.yaml
  - logstash-config.yaml
  - logstash-settings.yaml
  - logstash.yaml
  - kibana.yaml
  - kibana-ingress.yaml
  - monitoring-agent.yaml
  - heartbeat.yaml
  - elastic-agent-config.yaml
  - elastic-agent-rbac.yaml
  - elastic-agent.yaml
  - mcp.yaml
