apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  logstash.conf: |
    input {
      rabbitmq {
        host => "${RABBITMQ_HOST}"
        port => 5672
        user => "${RABBITMQ_USER}"
        password => "${RABBITMQ_PASS}"
        vhost => "/"
        queue => "monitoring.logs"
        durable => true
        auto_delete => false
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}"]
        user => "${ELASTICSEARCH_USER}"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "shift-logs-%{+YYYY.MM.dd}"
      }
    }
