name: CI Pipeline

on:
  push:
    branches: [ "main", "dev", "prod" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "dev", "prod" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests (Placeholder)
        run: |
          echo "Beste teams: Zet hier jullie eigen test-commando's!"
          echo "Als deze falen, zal Infra de image NIET bouwen."
          exit 0
