apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-phpmyadmin
  template:
    metadata:
      labels:
        app: frontend-phpmyadmin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        fsGroup: 33
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2-apache
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: frontend-db-service
        - name: PMA_PORT
          value: "3306"
        - name: UPLOAD_LIMIT
          value: "64M"
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-phpmyadmin-service
spec:
  type: NodePort
  selector:
    app: frontend-phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30022
