apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shift-festival-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      ghcr.io/integrationproject-groep1/ip-groep1-frontend,
      ghcr.io/integrationproject-groep1/kassa,
      ghcr.io/integrationproject-groep1/facturatie,
      ghcr.io/integrationproject-groep1/crm,
      ghcr.io/integrationproject-groep1/planning,
      ghcr.io/integrationproject-groep1/identity-service,
      ghcr.io/integrationproject-groep1/heartbeat,
      ghcr.io/integrationproject-groep1/monitoring
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/ip-groep1-frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/ip-groep1-frontend.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/kassa.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/kassa.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/facturatie.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/facturatie.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/crm.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/crm.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/planning.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/planning.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/identity-service.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/identity-service.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/heartbeat.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/heartbeat.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/monitoring.update-strategy: digest
    argocd-image-updater.argoproj.io/ghcr.io/integrationproject-groep1/monitoring.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: overlays/dev/kustomization.yaml
    argocd-image-updater.argoproj.io/git-branch: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/integrationproject-groep1/Infra.git
    targetRevision: dev
    path: overlays/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: shift-festival-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: shift-secrets
      jsonPointers:
        - /data
