apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/integrationproject-groep1/Infra.git
    targetRevision: main
    path: base/core/ingress
  destination:
    server: https://kubernetes.default.svc
    # No namespace here, the manifests define their own (ingress-nginx)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
