apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shift-festival-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      frontend=ghcr.io/integrationproject-groep1/ip-groep1-frontend:prod,
      kassa=ghcr.io/integrationproject-groep1/kassa:prod,
      facturatie=ghcr.io/integrationproject-groep1/facturatie:prod,
      crm=ghcr.io/integrationproject-groep1/crm:prod,
      planning=ghcr.io/integrationproject-groep1/planning:prod,
      identity=ghcr.io/integrationproject-groep1/identity-service:prod,
      heartbeat=ghcr.io/integrationproject-groep1/heartbeat:prod
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/integrationproject-groep1/Infra.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: shift-festival
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: shift-secrets
      jsonPointers:
        - /data
