apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      project: shift-festival
      managed-by: Team-Infra
    includeSelectors: false

resources:
  - setup/
  - core/
  - team-frontend/
  - team-kassa/
  - team-facturatie/
  - integrations/
  - monitoring/
