apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - configmaps.yaml

generatorOptions:
    disableNameSuffixHash: true

secretGenerator:
  - name: shift-secrets
    envs:
      - .env
