apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facturatie-ingress
  namespace: shift-festival
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-set-headers: "shift-festival/nginx-proxy-headers"
spec:
  ingressClassName: nginx
  rules:
  - host: facturatie.desiderius.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: facturatie-app-service
            port:
              number: 80
